-- liquibase formatted sql

-- changeset svn13:1686093144960-1
CREATE TABLE answer
(
    id                      BIGINT  NOT NULL,
    persist_date            TIMESTAMP WITHOUT TIME ZONE,
    update_date             TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    question_id             BIGINT  NOT NULL,
    user_id                 BIGINT  NOT NULL,
    html_body               TEXT    NOT NULL,
    is_helpful              BOOLEAN NOT NULL,
    is_deleted              BOOLEAN NOT NULL,
    is_deleted_by_moderator BOOLEAN NOT NULL,
    date_accept_time        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_answer PRIMARY KEY (id)
);

-- changeset svn13:1686093144960-2
CREATE TABLE badges
(
    id                    BIGINT NOT NULL,
    badge_name            VARCHAR(255),
    reputations_for_merit INTEGER,
    description           VARCHAR(255),
    CONSTRAINT pk_badges PRIMARY KEY (id)
);

-- changeset svn13:1686093144960-3
CREATE TABLE bookmarks
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     BIGINT                                  NOT NULL,
    question_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_bookmarks PRIMARY KEY (id)
);

-- changeset svn13:1686093144960-4
CREATE TABLE chat
(
    id           BIGINT NOT NULL,
    title        VARCHAR(255),
    persist_date TIMESTAMP WITHOUT TIME ZONE,
    chat_type    INTEGER,
    CONSTRAINT pk_chat PRIMARY KEY (id)
);

-- changeset svn13:1686093144960-5
CREATE TABLE comment
(
    id                  BIGINT       NOT NULL,
    text                VARCHAR(255) NOT NULL,
    comment_type        INTEGER      NOT NULL,
    persist_date        TIMESTAMP WITHOUT TIME ZONE,
    last_redaction_date TIMESTAMP WITHOUT TIME ZONE,
    user_id             BIGINT       NOT NULL,
    CONSTRAINT pk_comment PRIMARY KEY (id)
);

-- changeset svn13:1686093144960-6
CREATE TABLE comment_answer
(
    comment_id BIGINT NOT NULL,
    answer_id  BIGINT NOT NULL,
    CONSTRAINT pk_comment_answer PRIMARY KEY (comment_id)
);

-- changeset svn13:1686093144960-7
CREATE TABLE comment_question
(
    comment_id  BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    CONSTRAINT pk_comment_question PRIMARY KEY (comment_id)
);

-- changeset svn13:1686093144960-8
CREATE TABLE group_chat
(
    chat_id BIGINT NOT NULL,
    CONSTRAINT pk_group_chat PRIMARY KEY (chat_id)
);

-- changeset svn13:1686093144960-9
CREATE TABLE groupchat_has_users
(
    chat_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_groupchat_has_users PRIMARY KEY (chat_id, user_id)
);

-- changeset svn13:1686093144960-10
CREATE TABLE message
(
    id                  BIGINT NOT NULL,
    message             TEXT,
    last_redaction_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    persist_date        TIMESTAMP WITHOUT TIME ZONE,
    user_sender_id      BIGINT NOT NULL,
    chat_id             BIGINT NOT NULL,
    CONSTRAINT pk_message PRIMARY KEY (id)
);

-- changeset svn13:1686093144960-11
CREATE TABLE question
(
    id                  BIGINT       NOT NULL,
    title               VARCHAR(255) NOT NULL,
    description         TEXT         NOT NULL,
    persist_date        TIMESTAMP WITHOUT TIME ZONE,
    user_id             BIGINT       NOT NULL,
    last_redaction_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    is_deleted          BOOLEAN,
    CONSTRAINT pk_question PRIMARY KEY (id)
);

-- changeset svn13:1686093144960-12
CREATE TABLE question_has_tag
(
    question_id BIGINT NOT NULL,
    tag_id      BIGINT NOT NULL
);

-- changeset svn13:1686093144960-13
CREATE TABLE question_viewed
(
    id           BIGINT NOT NULL,
    user_id      BIGINT,
    question_id  BIGINT,
    persist_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_question_viewed PRIMARY KEY (id)
);

-- changeset svn13:1686093144960-14
CREATE TABLE related_tag
(
    id        BIGINT NOT NULL,
    main_tag  BIGINT NOT NULL,
    child_tag BIGINT NOT NULL,
    CONSTRAINT pk_related_tag PRIMARY KEY (id)
);

-- changeset svn13:1686093144960-15
CREATE TABLE reputation
(
    id           BIGINT  NOT NULL,
    persist_date TIMESTAMP WITHOUT TIME ZONE,
    author_id    BIGINT  NOT NULL,
    sender_id    BIGINT,
    count        INTEGER,
    type         INTEGER NOT NULL,
    question_id  BIGINT,
    answer_id    BIGINT,
    CONSTRAINT pk_reputation PRIMARY KEY (id)
);

-- changeset svn13:1686093144960-16
CREATE TABLE role
(
    id   BIGINT NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_role PRIMARY KEY (id)
);

-- changeset svn13:1686093144960-17
CREATE TABLE singel_chat
(
    chat_id     BIGINT NOT NULL,
    user_one_id BIGINT NOT NULL,
    use_two_id  BIGINT NOT NULL,
    CONSTRAINT pk_singel_chat PRIMARY KEY (chat_id)
);

-- changeset svn13:1686093144960-18
CREATE TABLE tag
(
    id           BIGINT       NOT NULL,
    name         VARCHAR(255) NOT NULL,
    description  VARCHAR(255),
    persist_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_tag PRIMARY KEY (id)
);

-- changeset svn13:1686093144960-19
CREATE TABLE tag_ignore
(
    id             BIGINT NOT NULL,
    ignored_tag_id BIGINT NOT NULL,
    user_id        BIGINT NOT NULL,
    persist_date   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_tag_ignore PRIMARY KEY (id)
);

-- changeset svn13:1686093144960-20
CREATE TABLE tag_tracked
(
    id             BIGINT NOT NULL,
    tracked_tag_id BIGINT NOT NULL,
    user_id        BIGINT NOT NULL,
    persist_date   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_tag_tracked PRIMARY KEY (id)
);

-- changeset svn13:1686093144960-21
CREATE TABLE user_badges
(
    id        BIGINT NOT NULL,
    ready     BOOLEAN,
    user_id   BIGINT,
    badges_id BIGINT,
    CONSTRAINT pk_user_badges PRIMARY KEY (id)
);

-- changeset svn13:1686093144960-22
CREATE TABLE user_entity
(
    id                  BIGINT NOT NULL,
    email               VARCHAR(255),
    password            VARCHAR(255),
    full_name           VARCHAR(255),
    persist_date        TIMESTAMP WITHOUT TIME ZONE,
    is_enabled          BOOLEAN,
    is_deleted          BOOLEAN,
    city                VARCHAR(255),
    link_site           VARCHAR(255),
    link_github         VARCHAR(255),
    link_vk             VARCHAR(255),
    about               VARCHAR(255),
    image_link          VARCHAR(255),
    last_redaction_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    nickname            VARCHAR(255),
    role_id             BIGINT NOT NULL,
    CONSTRAINT pk_user_entity PRIMARY KEY (id)
);

-- changeset svn13:1686093144960-23
CREATE TABLE user_favorite_question
(
    id           BIGINT NOT NULL,
    persist_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    user_id      BIGINT NOT NULL,
    question_id  BIGINT NOT NULL,
    CONSTRAINT pk_user_favorite_question PRIMARY KEY (id)
);

-- changeset svn13:1686093144960-24
CREATE TABLE votes_on_answers
(
    id           BIGINT NOT NULL,
    user_id      BIGINT NOT NULL,
    answer_id    BIGINT NOT NULL,
    persist_date TIMESTAMP WITHOUT TIME ZONE,
    vote_type    VARCHAR(255),
    CONSTRAINT pk_votes_on_answers PRIMARY KEY (id)
);

-- changeset svn13:1686093144960-25
CREATE TABLE votes_on_questions
(
    id           BIGINT NOT NULL,
    user_id      BIGINT,
    question_id  BIGINT,
    persist_date TIMESTAMP WITHOUT TIME ZONE,
    vote         VARCHAR(255),
    CONSTRAINT pk_votes_on_questions PRIMARY KEY (id)
);

-- changeset svn13:1686093144960-26
ALTER TABLE answer
    ADD CONSTRAINT FK_ANSWER_ON_QUESTION FOREIGN KEY (question_id) REFERENCES question (id);

-- changeset svn13:1686093144960-27
ALTER TABLE answer
    ADD CONSTRAINT FK_ANSWER_ON_USER FOREIGN KEY (user_id) REFERENCES user_entity (id);

-- changeset svn13:1686093144960-28
ALTER TABLE bookmarks
    ADD CONSTRAINT FK_BOOKMARKS_ON_QUESTION FOREIGN KEY (question_id) REFERENCES question (id);

-- changeset svn13:1686093144960-29
ALTER TABLE bookmarks
    ADD CONSTRAINT FK_BOOKMARKS_ON_USER FOREIGN KEY (user_id) REFERENCES user_entity (id);

-- changeset svn13:1686093144960-30
ALTER TABLE comment_answer
    ADD CONSTRAINT FK_COMMENT_ANSWER_ON_ANSWER FOREIGN KEY (answer_id) REFERENCES answer (id);

-- changeset svn13:1686093144960-31
ALTER TABLE comment_answer
    ADD CONSTRAINT FK_COMMENT_ANSWER_ON_COMMENT FOREIGN KEY (comment_id) REFERENCES comment (id);

-- changeset svn13:1686093144960-32
ALTER TABLE comment
    ADD CONSTRAINT FK_COMMENT_ON_USER FOREIGN KEY (user_id) REFERENCES user_entity (id);

-- changeset svn13:1686093144960-33
ALTER TABLE comment_question
    ADD CONSTRAINT FK_COMMENT_QUESTION_ON_COMMENT FOREIGN KEY (comment_id) REFERENCES comment (id);

-- changeset svn13:1686093144960-34
ALTER TABLE comment_question
    ADD CONSTRAINT FK_COMMENT_QUESTION_ON_QUESTION FOREIGN KEY (question_id) REFERENCES question (id);

-- changeset svn13:1686093144960-35
ALTER TABLE group_chat
    ADD CONSTRAINT FK_GROUP_CHAT_ON_CHAT FOREIGN KEY (chat_id) REFERENCES chat (id);

-- changeset svn13:1686093144960-36
ALTER TABLE message
    ADD CONSTRAINT FK_MESSAGE_ON_CHAT FOREIGN KEY (chat_id) REFERENCES chat (id);

-- changeset svn13:1686093144960-37
ALTER TABLE message
    ADD CONSTRAINT FK_MESSAGE_ON_USERSENDER FOREIGN KEY (user_sender_id) REFERENCES user_entity (id);

-- changeset svn13:1686093144960-38
ALTER TABLE question
    ADD CONSTRAINT FK_QUESTION_ON_USER FOREIGN KEY (user_id) REFERENCES user_entity (id);

-- changeset svn13:1686093144960-39
ALTER TABLE question_viewed
    ADD CONSTRAINT FK_QUESTION_VIEWED_ON_QUESTION FOREIGN KEY (question_id) REFERENCES question (id);

-- changeset svn13:1686093144960-40
ALTER TABLE question_viewed
    ADD CONSTRAINT FK_QUESTION_VIEWED_ON_USER FOREIGN KEY (user_id) REFERENCES user_entity (id);

-- changeset svn13:1686093144960-41
ALTER TABLE related_tag
    ADD CONSTRAINT FK_RELATED_TAG_ON_CHILD_TAG FOREIGN KEY (child_tag) REFERENCES tag (id);

-- changeset svn13:1686093144960-42
ALTER TABLE related_tag
    ADD CONSTRAINT FK_RELATED_TAG_ON_MAIN_TAG FOREIGN KEY (main_tag) REFERENCES tag (id);

-- changeset svn13:1686093144960-43
ALTER TABLE reputation
    ADD CONSTRAINT FK_REPUTATION_ON_ANSWER FOREIGN KEY (answer_id) REFERENCES answer (id);

-- changeset svn13:1686093144960-44
ALTER TABLE reputation
    ADD CONSTRAINT FK_REPUTATION_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES user_entity (id);

-- changeset svn13:1686093144960-45
ALTER TABLE reputation
    ADD CONSTRAINT FK_REPUTATION_ON_QUESTION FOREIGN KEY (question_id) REFERENCES question (id);

-- changeset svn13:1686093144960-46
ALTER TABLE reputation
    ADD CONSTRAINT FK_REPUTATION_ON_SENDER FOREIGN KEY (sender_id) REFERENCES user_entity (id);

-- changeset svn13:1686093144960-47
ALTER TABLE singel_chat
    ADD CONSTRAINT FK_SINGEL_CHAT_ON_CHAT FOREIGN KEY (chat_id) REFERENCES chat (id);

-- changeset svn13:1686093144960-48
ALTER TABLE singel_chat
    ADD CONSTRAINT FK_SINGEL_CHAT_ON_USERONE FOREIGN KEY (user_one_id) REFERENCES user_entity (id);

-- changeset svn13:1686093144960-49
ALTER TABLE singel_chat
    ADD CONSTRAINT FK_SINGEL_CHAT_ON_USETWO FOREIGN KEY (use_two_id) REFERENCES user_entity (id);

-- changeset svn13:1686093144960-50
ALTER TABLE tag_ignore
    ADD CONSTRAINT FK_TAG_IGNORE_ON_IGNOREDTAG FOREIGN KEY (ignored_tag_id) REFERENCES tag (id);

-- changeset svn13:1686093144960-51
ALTER TABLE tag_ignore
    ADD CONSTRAINT FK_TAG_IGNORE_ON_USER FOREIGN KEY (user_id) REFERENCES user_entity (id);

-- changeset svn13:1686093144960-52
ALTER TABLE tag_tracked
    ADD CONSTRAINT FK_TAG_TRACKED_ON_TRACKEDTAG FOREIGN KEY (tracked_tag_id) REFERENCES tag (id);

-- changeset svn13:1686093144960-53
ALTER TABLE tag_tracked
    ADD CONSTRAINT FK_TAG_TRACKED_ON_USER FOREIGN KEY (user_id) REFERENCES user_entity (id);

-- changeset svn13:1686093144960-54
ALTER TABLE user_badges
    ADD CONSTRAINT FK_USER_BADGES_ON_BADGES FOREIGN KEY (badges_id) REFERENCES badges (id);

-- changeset svn13:1686093144960-55
ALTER TABLE user_badges
    ADD CONSTRAINT FK_USER_BADGES_ON_USER FOREIGN KEY (user_id) REFERENCES user_entity (id);

-- changeset svn13:1686093144960-56
ALTER TABLE user_entity
    ADD CONSTRAINT FK_USER_ENTITY_ON_ROLE FOREIGN KEY (role_id) REFERENCES role (id);

-- changeset svn13:1686093144960-57
ALTER TABLE user_favorite_question
    ADD CONSTRAINT FK_USER_FAVORITE_QUESTION_ON_QUESTION FOREIGN KEY (question_id) REFERENCES question (id);

-- changeset svn13:1686093144960-58
ALTER TABLE user_favorite_question
    ADD CONSTRAINT FK_USER_FAVORITE_QUESTION_ON_USER FOREIGN KEY (user_id) REFERENCES user_entity (id);

-- changeset svn13:1686093144960-59
ALTER TABLE votes_on_answers
    ADD CONSTRAINT FK_VOTES_ON_ANSWERS_ON_ANSWER FOREIGN KEY (answer_id) REFERENCES answer (id);

-- changeset svn13:1686093144960-60
ALTER TABLE votes_on_answers
    ADD CONSTRAINT FK_VOTES_ON_ANSWERS_ON_USER FOREIGN KEY (user_id) REFERENCES user_entity (id);

-- changeset svn13:1686093144960-61
ALTER TABLE votes_on_questions
    ADD CONSTRAINT FK_VOTES_ON_QUESTIONS_ON_QUESTION FOREIGN KEY (question_id) REFERENCES question (id);

-- changeset svn13:1686093144960-62
ALTER TABLE votes_on_questions
    ADD CONSTRAINT FK_VOTES_ON_QUESTIONS_ON_USER FOREIGN KEY (user_id) REFERENCES user_entity (id);

-- changeset svn13:1686093144960-63
ALTER TABLE groupchat_has_users
    ADD CONSTRAINT fk_grohasuse_on_group_chat FOREIGN KEY (chat_id) REFERENCES group_chat (chat_id);

-- changeset svn13:1686093144960-64
ALTER TABLE groupchat_has_users
    ADD CONSTRAINT fk_grohasuse_on_user FOREIGN KEY (user_id) REFERENCES user_entity (id);

-- changeset svn13:1686093144960-65
ALTER TABLE question_has_tag
    ADD CONSTRAINT fk_quehastag_on_question FOREIGN KEY (question_id) REFERENCES question (id);

-- changeset svn13:1686093144960-66
ALTER TABLE question_has_tag
    ADD CONSTRAINT fk_quehastag_on_tag FOREIGN KEY (tag_id) REFERENCES tag (id);


